version: "3.7"
services:
  gunbot:
    image: blackbird7181/gunbot:18.8.8
    ports:
      - "5555:5000"
    environment:
      - TZ=America/Chicago
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/share/Data/container-station-data/config/gunbot/backups:/gunbot/backups"
      - "/share/Data/container-station-data/config/gunbot/logs:/gunbot/logs" 
      - "/share/Data/container-station-data/config/gunbot/json:/gunbot/json"
      - "/share/Data/container-station-data/config/gunbot/config.js:/gunbot/config.js"
      - "/share/Data/container-station-data/config/gunbot/gunbotgui.db:/gunbot/gunbotgui.db"
      - "/share/Data/container-station-data/config/gunbot/ssl.key:/gunbot/ssl.key"
      - "/share/Data/container-station-data/config/gunbot/ssl.crt:/gunbot/ssl.crt"
      - "/share/Data/container-station-data/config/gunbot/tgconfig.json:/gunbot/tgconfig.json"